sudo: false
language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install tox-travis coveralls

before_script:
  - psql -c 'create database timezone_field_tests;' -U postgres

script:
  - tox

after_success:
  - coveralls
